[tool.uv]
dev-dependencies = [
    "lambeq[extras,test]>=0.4.3",
    "nbformat~=5.7.3",
    "nbsphinx~=0.8.12",
    "numpydoc~=1.5.0",
    "Sphinx~=6.1.3",
    "sphinx-argparse~=0.4.0",
    "sphinx_mdinclude~=0.5.3",
    "furo~=2024.7.18",
    "sphinxcontrib-jquery~=4.1",
    "nbmake>=1.5.4",
    "pip>=24.2",
    "qiskit<1",
    "pytket-qiskit>=0.48.0",
    "qiskit-ibm-runtime>=0.17.0",
]

[tool.uv.workspace]
members = []
