[tool.uv]
dev-dependencies = [
    "lambeq[experimental,extras,test]>=0.4.2",
    "nbformat~=5.7.3",
    "myst_nb==1.1.*",
    "numpydoc~=1.5.0",
    "sphinx==7.4.*",
    "sphinx-argparse~=0.4.0",
    "sphinx_mdinclude~=0.5.3",
    "furo~=2024.7.18",
    "sphinx-copybutton==0.5.2",
    "sphinxcontrib-jquery~=4.1",
    "sphinxcontrib-bibtex~=2.6.3",
    "nbmake>=1.5.4",
    "pip>=24.2",
    "qiskit<1",
    "pytket-qiskit>=0.48.0",
    "qiskit-ibm-runtime>=0.17.0",
    "sphinxcontrib-googleanalytics==0.4",
]

[tool.uv.workspace]
members = []

[tool.uv.sources]
lambeq = { git = "https://github.com/cqcl/lambeq" }
