@startuml

set namespaceseparator none
skinparam dpi 96
skinparam ArrowColor Black
skinparam shadowing true
skinparam class {
  backgroundColor Business
  borderColor Red
}
skinparam object {
  backgroundColor lavender
  borderColor black
}


object lambdify

class Symbol {
    name
    directed_dom
    directed_cod
    scale
    unscaled
    size
    to_sympy()
}


Symbol -- lambdify : < takes

@enduml
